### ISSUE TITLE
idea / example: capture scripted puppeteer

### ISSUE THREAD

**Issue by DanielRuf** [styfle/magnemite#69]
Just an idea for an actual repo or as example.

If we provide a JS file which contains commands for puppeteer or uses puppeteer, execute / run it and record it.

Or is there already something like this?

**Comment by styfle** [comment]
Hi Daniel,

I'm not sure I understand. Are you suggesting that someone could use puppeteer to implement a similar tool as Magnemite?

I think puppeteer would not work for this use case because it's headless and we need to actually mimic the browser so the user can visit websites and browse as they normally would.

Or maybe I misunderstood your idea 😅

**Comment by DanielRuf** [comment]
No, I mean I am looking for an example to screencap a scripted Chrome instance using a puppeteer script.

Is this possible with magnemite?

**Comment by DanielRuf** [comment]
You can also disable the headless mode in the puppeteer options (headful mode), so this is not an issue,

**Comment by DanielRuf** [comment]
But maybe I just think too complicated.

**Comment by styfle** [comment]
> I am looking for an example to screencap a scripted Chrome instance using a puppeteer script.

Unfortunately, Magnemite does not use puppeteer...it's built on Electron and uses the [desktopCapturer](https://electronjs.org/docs/api/desktop-capturer) API to record the screen as seen in [/src/capturer.ts](https://github.com/styfle/magnemite/blob/master/src/capturer.ts).

I didn't realize puppeteer had a chrome (`headless: false`) available! You might be able to use the chrome API to record the screen and somehow send it to puppeteer's node API (not sure how this bridge works since I haven't used puppeteer).

There is an open issue for a screencast feature https://github.com/GoogleChrome/puppeteer/issues/478

Let me know what you come up with 😄
